---
# Source: cost-analyzer/charts/prometheus/templates/kube-state-metrics-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    component: "kube-state-metrics"
    app: prometheus
    release: RELEASE-NAME
    chart: prometheus-8.15.0
    heritage: Helm
  name: RELEASE-NAME-prometheus-kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: RELEASE-NAME-prometheus-kube-state-metrics
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: RELEASE-NAME-prometheus-kube-state-metrics
